### ISSUE TITLE
Selected file could not be built

### ISSUE THREAD

**Issue by riccardocescon** [nivisi/vscode-dart-build-runner-tools#5]
Today i have updated the extension, currently on v1.2.1
When i try to build a .freezed file i get:
Selected file could not be built. Most likely there is no suitable pubspec.yaml found.

Before the update i had no issues building

By writing dart run build_runner build --delete-conflicting-outputs on CLI it works

**Comment by nivisi** [comment]
@riccardocescon thank you. This has been fixed in `1.2.2`. The package is published & should soon become available.

**Comment by riccardocescon** [comment]
Thank you!
I have just updated to v1.2.2 but still this issue exists.
Same message
@nivisi

**Comment by nivisi** [comment]
@riccardocescon can you show me your folder structure please? As I was able to reproduce the issue on 1.2.1, but not on 1.2.2

**Comment by riccardocescon** [comment]
Sure @nivisi 
I am using Clean Architecture with Bloc, so under my feature/presentation/pages/homepage/ i have:
homepage_bloc.dart, homepage_event.dart, homepage_state.dart, these last 2 are a part of of the bloc.
I also have a homepage_bloc.freezed.dart, the issue happens when i right click on the freezed file and try to regenerate it

**Comment by nivisi** [comment]
@riccardocescon I still can't reproduce the issue. Could you please send me the error that you see in the console? One thing I can recommend to double check if you've actually updated to 1.2.2.

I have tried with different workspaces:

1. That has only one project, in the root
  
   ```
   *files*
   lib/
     ...
   pubspec.yaml
   ```

2. That has a root project + a package
  
   ```
   *files*
   packages/
     package/
       lib/
         ...
       pubspec.yaml
   lib/
     ...
   pubspec.yaml
   ```

3. That has multiple nested projects
   
   ```
   *files*
   packages/
     package_1/
       lib/
         ...
       pubspec.yaml
     package_2/
       lib/
         ...
       pubspec.yaml
   ```

**Comment by riccardocescon** [comment]
@nivisi 
It does not create a terminal. it crashes before that. I am getting this warning:
![image](https://github.com/user-attachments/assets/441fdede-9dc8-4e48-b90d-dc895388debe)

And here is the extension:
![image](https://github.com/user-attachments/assets/3484c39b-0516-4004-bf47-1fce174600e1)

**Comment by nivisi** [comment]
@riccardocescon does your file structure look something like this? If not, could you please send it to me in the below format?

```
*root*

lib/
  feature/
    presentation/
      pages/
        homepage/
          homepage_bloc.dart
          homepage_bloc.freezed.dart
pubspec.yaml
```

**Comment by riccardocescon** [comment]
@nivisi Yes, it is similar. here it is:
```
lib/
    features/
        app_name/
            presentation/
                bloc/
                    pages/
                        homepage/
                            homepage_bloc.dart
                            homepage_event.dart
                            homepage_state.dart
                            homepage_bloc.freezed.dart
pubspec.yaml
```

**Comment by nivisi** [comment]
@riccardocescon what is printed in the terminal?

**Comment by nivisi** [comment]
Does your `pubspec.yaml` have the `build_runner` dependency?

**Comment by riccardocescon** [comment]
@nivisi Nothing is printed on the terminal
Yes it does, i have build_runner: ^2.4.8

**Comment by nivisi** [comment]
@riccardocescon I've tried to reproduce it with a few other setups, but I couldn't. The files are getting built properly. 

If you have time, could you please create a repo with the minimum code required to reproduce the issue? Otherwise I will try to further explore what could cause this behaviour. I will also update `README` to describe requirements for the extension to function properly. But based on your structure, I see the required conditions are met:

1. There's a `lib` folder on the same level with the `pubspec.yaml` file
2. The `pubspec.yaml` has a dependency on `build_runner`
3. The command is executed on a generated file (`freezed` in this case).

**Comment by riccardocescon** [comment]
@nivisi Here it is:
https://github.com/riccardocescon/build_runner_failure_template

Simply right click on test_bloc.dart and select  
build_runner: Build Part Files 
causes this issue

**Comment by nivisi** [comment]
@riccardocescon works for me:

https://github.com/user-attachments/assets/b777eea8-a085-4716-8cd9-2e5408c34b1a

**Comment by riccardocescon** [comment]
@nivisi  Heres what happens to me
https://github.com/user-attachments/assets/893a6fb1-cad2-410b-a52b-026f0955f0cd

**Comment by nivisi** [comment]
@riccardocescon I was just going to ask what is the path that you have. Perhaps it fails at that moment. I will have a look. At this moment, I recommend you falling back to `1.1.1` until the issue is resolved. You can do it by going to the extension page in VSCode -> `Uninstall` dropdown -> `Install specific version` -> `1.1.1`.

I will update you once I fix it

**Comment by riccardocescon** [comment]
@nivisi i just downgraded to v1.1.1
I am a heavy user of this extension so if i can provide you any other usefull information let me know!

**Comment by nivisi** [comment]
@riccardocescon hi sir! Could you please try it on the version `1.2.4`? It was just published, must become available soon.

**Comment by riccardocescon** [comment]
@nivisi Hi, works perfectly, thank you!
